package com.stockflow.audit;

public enum AuditAction {
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    INVENTORY_MOVEMENT_CREATED,
    PURCHASE_ORDER_RECEIVED,
    SALES_ORDER_SHIPPED,
    LEDGER_TRANSACTION_CREATED,
    USER_CREATED,
    USER_BOOTSTRAPPED
}
