package com.stockflow.exception;

public enum ApiErrorCode {
    RESOURCE_NOT_FOUND,
    DUPLICATE_RESOURCE,
    INVALID_CREDENTIALS,
    AUTHENTICATION_REQUIRED,
    ACCESS_DENIED,
    VALIDATION_FAILED,
    BUSINESS_RULE_VIOLATION,
    INTERNAL_ERROR,

    INVENTORY_POSITIVE_QUANTITY_REQUIRED,
    INSUFFICIENT_STOCK,
    SUPPLIER_HAS_PRODUCTS,

    PURCHASE_ORDER_RECEIVE_WORKFLOW_REQUIRED,
    PURCHASE_ORDER_CANCELLED,
    PURCHASE_ORDER_ITEMS_REQUIRED,
    PURCHASE_ORDER_ALREADY_RECEIVED,
    PURCHASE_ORDER_NOT_ORDERED,
    PURCHASE_ORDER_RECEIVED_DELETE_FORBIDDEN,
    PURCHASE_ORDER_NOT_DRAFT,

    SALES_ORDER_SHIP_WORKFLOW_REQUIRED,
    SALES_ORDER_CANCELLED,
    SALES_ORDER_SHIPPED,
    SALES_ORDER_NOT_CONFIRMED,
    SALES_ORDER_ALREADY_SHIPPED,
    SALES_ORDER_NOT_PAID,
    SALES_ORDER_SHIPPED_DELETE_FORBIDDEN,
    SALES_ORDER_NOT_DRAFT,
    SALES_ORDER_ITEMS_REQUIRED
}
